USE [master]
GO
CREATE DATABASE [Nessus]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nessus', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Nessus.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Nessus_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Nessus_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Nessus] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nessus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Nessus] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Nessus] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Nessus] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Nessus] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Nessus] SET ARITHABORT OFF 
GO
ALTER DATABASE [Nessus] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Nessus] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Nessus] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Nessus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Nessus] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Nessus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Nessus] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Nessus] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Nessus] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Nessus] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Nessus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Nessus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Nessus] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Nessus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Nessus] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Nessus] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Nessus] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Nessus] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Nessus] SET  MULTI_USER 
GO
ALTER DATABASE [Nessus] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Nessus] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Nessus] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Nessus] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Nessus] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Nessus] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Nessus] SET QUERY_STORE = OFF
GO
USE [Nessus]
GO
/****** Object:  Table [dbo].[ScanResuls]    Script Date: 2023-12-21 8:49:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ScanResuls](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HostName] [nvarchar](50) NOT NULL,
	[ScanDate] [datetime2](7) NOT NULL,
	[Output] [nvarchar](max) NOT NULL,
	[Severity] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ScanResuls] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Nessus] SET  READ_WRITE 
GO
